spring:
  application:
    name: eureka-server
server:
  port: 10032
eureka: # eureka config
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 3
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 这里的 defaultZone 不能写成 default-zone
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: false
