language: java
sudo: false
jdk:
  - openjdk8

script:
  - mvn clean package -Dmaven.test.skip=true
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f2d78fab-8a51-4208-a7e7-f6ef74e83687