spring:
  application:
    name: mail
  mail:
    host: smtp.163.com
    username: rexlin500@163.com
    password: springboot123456
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
server:
  port: 10019
