spring:
  application:
    name: oss
server:
  port: 10037
# oss config
# 注意七牛云的外链一般30天后会回收
oss:
  aliyun:
    enable: true
    domain: "http://rexlin600-blog.oss-cn-chengdu.aliyuncs.com"
    endpoint: "oss-cn-chengdu.aliyuncs.com"
    access-key: "xxx"
    access-key-secret: "xxx"
    bucket-name: "rexlin600-blog"
  tencent:
    enable: false
    domain: "http://rexlin600-1257869896.cos.ap-chengdu.myqcloud.com"
    secret-id: "xxx"
    secret-key: "xxx"
    region: "ap-chengdu"
    bucket-name: "test-1257869896"
  qiniu:
    enable: false
    domain: "http://qcb7l22vz.bkt.clouddn.com"
    access-key: "xxx"
    secret-key: "xxx"
    bucket-name: "rexlin600"
