spring:
  application:
    name: oss
server:
  port: 10037
# oss config
oss:
  aliyun:
    domain: ""
    endpoint: ""
    access-key: ""
    access-key-secret: ""
    bucket-name: ""
  tencent:
    domain: ""
    secret-id: ""
    secret-key: ""
    region: ""
    bucket-name: "